repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
        args: [--fix]
        files: ^services/.*\.py$
      - id: ruff-format
        files: ^services/.*\.py$
