"""Minimal OpenAI-compatible LLM mock for integration tests.

Handles POST /v1/chat/completions with a canned response and GET /health.
All requests are accepted; no authentication required.
"""

from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import BaseModel

app = FastAPI(title="LLM Mock")

MEMORY_YAML = """project_id: mock-project
last_updated: "2026-01-01T00:00:00Z"
last_ticket_id: mock-ticket
summary: Mock project memory generated by integration test LLM stub.
architecture:
  - Mock service architecture
recent_changes:
  - ticket_id: mock-ticket
    summary: Integration test ticket processed by mock LLM
    files_changed: []
    risks: []
open_risks:
  - None identified in mock run
known_constraints:
  - Mock environment only
tech_stack:
  backend: FastAPI/Python 3.12
  frontend: React/TypeScript
  database: PostgreSQL 16
  infra: Docker Compose
"""

CANNED_COMPLETION = {
    "id": "mock-chatcmpl-001",
    "object": "chat.completion",
    "created": 1700000000,
    "model": "gpt-4o-mock",
    "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": MEMORY_YAML,
            },
            "finish_reason": "stop",
        }
    ],
    "usage": {"prompt_tokens": 10, "completion_tokens": 80, "total_tokens": 90},
}


class ChatCompletionRequest(BaseModel):
    model: str = "gpt-4o-mock"
    messages: list = []

    class Config:
        extra = "allow"


@app.post("/v1/chat/completions")
async def chat_completions(body: ChatCompletionRequest):
    return JSONResponse(status_code=200, content=CANNED_COMPLETION)


@app.get("/health")
async def health():
    return {"status": "ok"}
